//Construir un modelo de datos constituido por un Array de 5 objetos llamados: pelicula1,
//pelicula2, pelicula3, pelicula4 y pelicula5, donde Cada uno de esos objetos tiene como atributo: id (código único de identificación IMDB ), título, director, país, año de estreno, género y calificación (por ejemplo IMDB). El año de estreno debe estar en el periodo de años consecutivos 1999, 2001, 2002, 2003 y 2004 (uno para cada objeto), dos películas deben ser del género “policíaco” y las tres restantes del género “comedia”. El orden de las películas en el Array debe ser de más antigua a más moderna por año de estreno.
//Cada objeto puede contener los datos de tu elección pero siempre bajo el criterio de darles los tipos más adecuados y las restricciones mencionadas en el anterior párrafo. 
 

